# Form implementation generated from reading ui file 'info_sys.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MyMainWindow(object):
    def setupUi(self, MyMainWindow):
        MyMainWindow.setObjectName("MyMainWindow")
        MyMainWindow.setEnabled(False)
        MyMainWindow.resize(1912, 1062)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MyMainWindow.sizePolicy().hasHeightForWidth())
        MyMainWindow.setSizePolicy(sizePolicy)
        MyMainWindow.setStyleSheet("background-image: url(:/images/background.png);")
        self.centralwidget = QtWidgets.QWidget(parent=MyMainWindow)
        self.centralwidget.setEnabled(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.main_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.main_button.setGeometry(QtCore.QRect(560, 390, 859, 299))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button.sizePolicy().hasHeightForWidth())
        self.main_button.setSizePolicy(sizePolicy)
        self.main_button.setStyleSheet("background-image: url(:/images/main_button.png);\n"
"border: 0;")
        self.main_button.setText("")
        self.main_button.setObjectName("main_button")
        self.main_hall = QtWidgets.QWidget(parent=self.centralwidget)
        self.main_hall.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.main_hall.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.main_hall.setObjectName("main_hall")
        self.jewerly = QtWidgets.QPushButton(parent=self.main_hall)
        self.jewerly.setGeometry(QtCore.QRect(153, 397, 527, 265))
        self.jewerly.setStyleSheet("background-image: url(:/main_hall/jewelry.png);\n"
"border: 0;")
        self.jewerly.setText("")
        self.jewerly.setObjectName("jewelry")
        self.embroidery = QtWidgets.QPushButton(parent=self.main_hall)
        self.embroidery.setGeometry(QtCore.QRect(721, 397, 527, 265))
        self.embroidery.setStyleSheet("background-image: url(:/main_hall/embroidery.png);\n"
"border: 0;")
        self.embroidery.setText("")
        self.embroidery.setObjectName("embroidery")
        self.painting = QtWidgets.QPushButton(parent=self.main_hall)
        self.painting.setGeometry(QtCore.QRect(1290, 397, 527, 265))
        self.painting.setStyleSheet("background-image: url(:/main_hall/painting.png);\n"
"border: 0;")
        self.painting.setText("")
        self.painting.setObjectName("painting")
        self.jewelry_widget = QtWidgets.QWidget(parent=self.main_hall)
        self.jewelry_widget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.jewelry_widget.setStyleSheet("background-image: url(:/jewelry/jewelry_bg.png);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border: 0;")
        self.jewelry_widget.setObjectName("jewelry_widget")
        self.jewelry_pass = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.jewelry_pass.setGeometry(QtCore.QRect(0, 285, 465, 110))
        self.jewelry_pass.setStyleSheet("background-image: url(:/left_menu/jewelry_menu.png);\n"
"border: 0;")
        self.jewelry_pass.setText("")
        self.jewelry_pass.setObjectName("jewelry_pass")
        self.masters = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.masters.setGeometry(QtCore.QRect(40, 392, 452, 121))
        self.masters.setStyleSheet("background-image: url(:/jewelry/masters.png);\n"
"border: 0;")
        self.masters.setText("")
        self.masters.setObjectName("masters")
        self.video_photo = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.video_photo.setGeometry(QtCore.QRect(40, 485, 452, 121))
        self.video_photo.setStyleSheet("background-image: url(:/jewelry/video_photo.png);\n"
"border: 0;")
        self.video_photo.setText("")
        self.video_photo.setObjectName("video_photo")
        self.embroidery_left = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.embroidery_left.setGeometry(QtCore.QRect(0, 643, 491, 160))
        self.embroidery_left.setStyleSheet("background-image: url(:/left_menu/embroidery_menu.png);\n"
"border: 0;")
        self.embroidery_left.setText("")
        self.embroidery_left.setObjectName("embroidery_left")
        self.painting_left = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.painting_left.setGeometry(QtCore.QRect(0, 791, 491, 121))
        self.painting_left.setStyleSheet("background-image: url(:/left_menu/painting_menu.png);\n"
"border: 0;")
        self.painting_left.setText("")
        self.painting_left.setObjectName("painting_left")
        self.pushButton = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.pushButton.setGeometry(QtCore.QRect(1110, 975, 166, 63))
        self.pushButton.setStyleSheet("background-image: url(:/images/back.png);\n"
"border: 0;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.photo_video = QtWidgets.QWidget(parent=self.jewelry_widget)
        self.photo_video.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.photo_video.setStyleSheet("background-image: url(:/jewelry/jewelry_bg.png);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border: 0;")
        self.photo_video.setObjectName("photo_video")
        self.jewelry_pass_2 = QtWidgets.QPushButton(parent=self.photo_video)
        self.jewelry_pass_2.setGeometry(QtCore.QRect(0, 285, 465, 110))
        self.jewelry_pass_2.setStyleSheet("background-image: url(:/left_menu/jewelry_menu.png);\n"
"border: 0;")
        self.jewelry_pass_2.setText("")
        self.jewelry_pass_2.setObjectName("jewelry_pass_2")
        self.masters_2 = QtWidgets.QPushButton(parent=self.photo_video)
        self.masters_2.setGeometry(QtCore.QRect(40, 392, 452, 121))
        self.masters_2.setStyleSheet("background-image: url(:/jewelry/masters.png);\n"
"border: 0;")
        self.masters_2.setText("")
        self.masters_2.setObjectName("masters_2")
        self.video_photo_2 = QtWidgets.QPushButton(parent=self.photo_video)
        self.video_photo_2.setGeometry(QtCore.QRect(40, 485, 452, 121))
        self.video_photo_2.setStyleSheet("background-image: url(:/jewelry/video_photo.png);\n"
"border: 0;")
        self.video_photo_2.setText("")
        self.video_photo_2.setObjectName("video_photo_2")
        self.embroidery_left_2 = QtWidgets.QPushButton(parent=self.photo_video)
        self.embroidery_left_2.setGeometry(QtCore.QRect(0, 643, 491, 160))
        self.embroidery_left_2.setStyleSheet("background-image: url(:/left_menu/embroidery_menu.png);\n"
"border: 0;")
        self.embroidery_left_2.setText("")
        self.embroidery_left_2.setObjectName("embroidery_left_2")
        self.painting_left_2 = QtWidgets.QPushButton(parent=self.photo_video)
        self.painting_left_2.setGeometry(QtCore.QRect(0, 791, 491, 121))
        self.painting_left_2.setStyleSheet("background-image: url(:/left_menu/painting_menu.png);\n"
"border: 0;")
        self.painting_left_2.setText("")
        self.painting_left_2.setObjectName("painting_left_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.photo_video)
        self.pushButton_2.setGeometry(QtCore.QRect(1110, 975, 166, 63))
        self.pushButton_2.setStyleSheet("background-image: url(:/images/back.png);\n"
"border: 0;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.video_title = QtWidgets.QLabel(parent=self.photo_video)
        self.video_title.setGeometry(QtCore.QRect(1007, 213, 370, 43))
        self.video_title.setStyleSheet("background-image: url(:/jewelry/video_title.png);\n"
"border: 0;")
        self.video_title.setText("")
        self.video_title.setObjectName("video_title")
        self.photo_title = QtWidgets.QLabel(parent=self.photo_video)
        self.photo_title.setGeometry(QtCore.QRect(1007, 600, 370, 43))
        self.photo_title.setStyleSheet("background-image: url(:/jewelry/photo_title.png);\n"
"border: 0;")
        self.photo_title.setText("")
        self.photo_title.setObjectName("photo_title")
        self.widget = QtWidgets.QWidget(parent=self.photo_video)
        self.widget.setGeometry(QtCore.QRect(530, 170, 1311, 791))
        self.widget.setStyleSheet("background: transparent;\n"
"border: 0;")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(480, 110, 361, 307))
        self.label_3.setStyleSheet("background-image: url(:/jewelry/play_preview.png);\n"
"border: 0;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.photo_left_button = QtWidgets.QPushButton(parent=self.widget)
        self.photo_left_button.setGeometry(QtCore.QRect(70, 600, 25, 64))
        self.photo_left_button.setStyleSheet("background-image: url(:/images/photo_left_button.png);\n"
"border: 0;")
        self.photo_left_button.setText("")
        self.photo_left_button.setObjectName("photo_left_button")
        self.photo_right_button = QtWidgets.QPushButton(parent=self.widget)
        self.photo_right_button.setGeometry(QtCore.QRect(1230, 600, 25, 64))
        self.photo_right_button.setStyleSheet("background-image: url(:/images/photo_right_button.png);\n"
"border: 0;")
        self.photo_right_button.setText("")
        self.photo_right_button.setObjectName("photo_right_button")
        MyMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MyMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MyMainWindow)

    def retranslateUi(self, MyMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MyMainWindow.setWindowTitle(_translate("MyMainWindow", "Museum"))
