# Form implementation generated from reading ui file 'info_sys.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MyMainWindow(object):
    def setupUi(self, MyMainWindow):
        MyMainWindow.setObjectName("MyMainWindow")
        MyMainWindow.setEnabled(False)
        MyMainWindow.resize(1916, 1071)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MyMainWindow.sizePolicy().hasHeightForWidth())
        MyMainWindow.setSizePolicy(sizePolicy)
        MyMainWindow.setStyleSheet("background-image: url(:/images/background.png);")
        self.centralwidget = QtWidgets.QWidget(parent=MyMainWindow)
        self.centralwidget.setEnabled(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.main_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.main_button.setGeometry(QtCore.QRect(560, 390, 859, 299))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button.sizePolicy().hasHeightForWidth())
        self.main_button.setSizePolicy(sizePolicy)
        self.main_button.setStyleSheet("background-image: url(:/images/main_button.png);\n"
"border: 0;")
        self.main_button.setText("")
        self.main_button.setObjectName("main_button")
        self.main_hall = QtWidgets.QWidget(parent=self.centralwidget)
        self.main_hall.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.main_hall.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.main_hall.setObjectName("main_hall")
        self.jewerly = QtWidgets.QPushButton(parent=self.main_hall)
        self.jewerly.setGeometry(QtCore.QRect(153, 397, 527, 265))
        self.jewerly.setStyleSheet("background-image: url(:/main_hall/jewelry.png);\n"
"border: 0;")
        self.jewerly.setText("")
        self.jewerly.setObjectName("jewerly")
        self.embroidery = QtWidgets.QPushButton(parent=self.main_hall)
        self.embroidery.setGeometry(QtCore.QRect(721, 397, 527, 265))
        self.embroidery.setStyleSheet("background-image: url(:/main_hall/embroidery.png);\n"
"border: 0;")
        self.embroidery.setText("")
        self.embroidery.setObjectName("embroidery")
        self.painting = QtWidgets.QPushButton(parent=self.main_hall)
        self.painting.setGeometry(QtCore.QRect(1290, 397, 527, 265))
        self.painting.setStyleSheet("background-image: url(:/main_hall/painting.png);\n"
"border: 0;")
        self.painting.setText("")
        self.painting.setObjectName("painting")
        self.jewelry_widget = QtWidgets.QWidget(parent=self.main_hall)
        self.jewelry_widget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.jewelry_widget.setStyleSheet("background-image: url(:/jewelry/jewelry_bg.png);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border: 0;")
        self.jewelry_widget.setObjectName("jewelry_widget")
        self.jewelry_pass = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.jewelry_pass.setGeometry(QtCore.QRect(0, 285, 465, 110))
        self.jewelry_pass.setStyleSheet("background-image: url(:/left_menu/jewelry_menu.png);\n"
"border: 0;")
        self.jewelry_pass.setText("")
        self.jewelry_pass.setObjectName("jewelry_pass")
        self.masters = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.masters.setGeometry(QtCore.QRect(40, 392, 452, 121))
        self.masters.setStyleSheet("background-image: url(:/jewelry/masters.png);\n"
"border: 0;")
        self.masters.setText("")
        self.masters.setObjectName("masters")
        self.video_photo = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.video_photo.setGeometry(QtCore.QRect(40, 485, 452, 121))
        self.video_photo.setStyleSheet("background-image: url(:/jewelry/video_photo.png);\n"
"border: 0;")
        self.video_photo.setText("")
        self.video_photo.setObjectName("video_photo")
        self.embroidery_left = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.embroidery_left.setGeometry(QtCore.QRect(0, 643, 491, 160))
        self.embroidery_left.setStyleSheet("background-image: url(:/left_menu/embroidery_menu.png);\n"
"border: 0;")
        self.embroidery_left.setText("")
        self.embroidery_left.setObjectName("embroidery_left")
        self.painting_left = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.painting_left.setGeometry(QtCore.QRect(0, 791, 491, 121))
        self.painting_left.setStyleSheet("background-image: url(:/left_menu/painting_menu.png);\n"
"border: 0;")
        self.painting_left.setText("")
        self.painting_left.setObjectName("painting_left")
        self.textEdit = QtWidgets.QTextEdit(parent=self.jewelry_widget)
        self.textEdit.setGeometry(QtCore.QRect(603, 229, 1174, 36))
        self.textEdit.setStyleSheet("background: transparent;\n"
"border: 0;")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.jewelry_widget)
        self.pushButton.setGeometry(QtCore.QRect(1110, 975, 166, 63))
        self.pushButton.setStyleSheet("background-image: url(:/images/back.png);\n"
"border: 0;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        MyMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MyMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MyMainWindow)

    def retranslateUi(self, MyMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MyMainWindow.setWindowTitle(_translate("MyMainWindow", "Museum"))
        self.textEdit.setHtml(_translate("MyMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; color:#aa0000;\">Test</span></p></body></html>"))
